### ISSUE TITLE
Select2.js custom select has lower z-index than ThickBox window

### ISSUE THREAD

**Issue by ocReaper** [katzwebservices/Bigcommerce-WordPress-Plugin#13]
Select2.js custom select list is displaying under the ThickBox window due to it has lower z-index.
The problem effects all browsers and as far as I know it's active since WP 4.0
The simple solution is modifing the following in select2.css from:
```css
.select2-drop {
  z-index: 9999;
}
```
to:
```css
.select2-drop {
  z-index: 100051; /*#TB_window uses 100050*/
}

**Comment by zackkatz** [comment]
Thanks!
